version: 2
jobs:
  setup:
    working_directory: ~/workspace/repo
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install
      - persist_to_workspace:
          root: "~/workspace"
          paths:
            - "repo"
  lint:
    docker:
      - image: circleci/node
    working_directory: ~/workspace/repo
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Lint
          command: npm run-script lint          
  karma:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/workspace/repo
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Karma tests
          environment: 
            CHROME_BIN: "/usr/bin/google-chrome"
          command: npm run-script test -- --watch=false
  jasmine:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/workspace/repo
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Jasmine tests
          command: npm run-script e2e -- --port=5000
  prod_deploy:
    docker:
      - image: circleci/node
    working_directory: ~/workspace/repo
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Prod deploy
          command: |
            npm run-script build -- --prod
            ./node_modules/.bin/firebase use production --token=$FIREBASE_DEPLOY_TOKEN
            ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN --non-interactive

workflows:
  version: 2
  ci:
    jobs:
      - setup
      - lint:
          requires: ['setup']
      - karma:
          requires: ['setup']
      - jasmine:
          requires: ['setup']
      - deploy_approval:
          type: approval
          requires: ['setup', 'lint', 'karma', 'jasmine']
          filters:
            branches:
              only: master
      - prod_deploy:
          requires: ['deploy_approval']
          filters:
            branches:
              only: master
