version: 2
jobs:
  setup:
    working_directory: ~/workspace/repo
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: npm install
      - persist_to_workspace:
          root: "~/workspace"
          paths:
            - "repo"
  lint:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/workspace/repo
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Lint
          command: npm run-script lint          
  test:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/workspace/repo
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Frontend tests
          environment: 
            CHROME_BIN: "/usr/bin/google-chrome"
          command: npm run-script test-no-watch
  prod_deploy:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/workspace/repo
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Prod deploy
          command: |
            npm run-script prod-build
            ./node_modules/.bin/firebase use production --token=$FIREBASE_DEPLOY_TOKEN
            ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN --non-interactive

workflows:
  version: 2
  ci:
    jobs:
      - setup
      - lint:
          requires: ['setup']
      - test:
          requires: ['setup']
      - deploy_approval:
          type: approval
          requires: ['setup', 'lint', 'test']
          filters:
            branches:
              only: master
      - prod_deploy:
          requires: ['setup', 'lint', 'test', 'deploy_approval']
          filters:
            branches:
              only: master

